### ISSUE TITLE
Declaration is not supported for swift

### ISSUE THREAD

**Issue by angelozerr** [swiftlang/sourcekit-lsp#1847] opened 2024-11-28 10:22 UTC
### Description

Your language server says that it supports declaration https://github.com/swiftlang/sourcekit-lsp/blob/3b6ced848805ba9b49f0872800b69abbf673d112/Sources/SourceKitLSP/SourceKitLSPServer.swift#L1055

It is true for c language but not for swift language. In vscode for instance, the menu `Go To Declaration` is enable for swift file

![image](https://github.com/user-attachments/assets/32d2177a-db80-4789-9643-1bbfb83011ed)

and when you execute it, it throws an error 

```
[Trace - 11:05:09 AM] Received response 'textDocument/declaration - (38)' in 41ms. Request failed: unsupported method (-32001).
[Error - 11:05:09 AM] Request textDocument/declaration failed.
  Message: unsupported method
  Code: -32001 
```

The `Go To Declaration` should be visible only for c files, but not for swift files. To do that and if LSP client like vscode, LSP4IJ etc support dynamic capabilities, you should send a registerCapability for declaration only for c, cpp, etc

```
[Trace - 11:03:56 AM] Received request 'client/registerCapability - (2)'.
Params: {
    "registrations": [
        {
            "id": "165E8362-B52A-4FD5-8026-7885DA379067",
            "method": "textDocument/declaration",
            "registerOptions": {
                "documentSelector": [
                    {
                        "language": "c"
                    },
                    {
                        "language": "cpp"
                    }
                   ...
                ]
            }
        }
    ]
}
```

**Comment by ahoppen** [comment] 2024-11-28 16:26
Synced to Apple’s issue tracker as rdar://140662916

**Comment by ahoppen** [comment] 2024-12-03 01:42
Did you build the project recently? I assume that we can’t find the declaration in the index and building would update the index. The `unsupported method (-32001)` error code is a little misleading here.

If doing a build doesn’t fix the issue, could you run `sourcekit-lsp diagnose` and attach the bundle to this issue? That should give us a hint about what’s going wrong.

**Comment by angelozerr** [comment] 2024-12-03 10:01
I have not build something. Just play with vscode-swift which have this problem with wrong declarationwprovider swift capability which shows the Go to declaration menu although it should be hidden

**Comment by ahoppen** [comment] 2024-12-03 22:16
Could you try if building your project fixes the problem? As stated in the README.

> SourceKit-LSP does not update its global index in the background or build Swift modules in the background. Thus, a lot of cross-module or global functionality is limited if the project hasn't been built recently. To update the index or rebuild the Swift modules, build your project or enable the experimental background indexing as described in [Enable Experimental Background Indexing](https://github.com/swiftlang/sourcekit-lsp/blob/main/Documentation/Enable%20Experimental%20Background%20Indexing.md).

**Comment by angelozerr** [comment] 2024-12-04 03:00
> Could you try if building your project fixes the problem? As stated in the README.
> 
> > SourceKit-LSP does not update its global index in the background or build Swift modules in the background. Thus, a lot of cross-module or global functionality is limited if the project hasn't been built recently. To update the index or rebuild the Swift modules, build your project or enable the experimental background indexing as described in [Enable Experimental Background Indexing](https://github.com/swiftlang/sourcekit-lsp/blob/main/Documentation/Enable%20Experimental%20Background%20Indexing.md).

@ahoppen I am sorry I have no time to do that because I.dont use swift. I wanted just to test your language server inside IntelliJ with LSP4IJ https://github.com/redhat-developer/lsp4ij/blob/main/docs/user-defined-ls/sourcekit-lsp.md and I have seen this error.

**Comment by ahoppen** [comment] 2024-12-04 04:16
OK, thanks for the feedback regardless. If you never performed a build, I am pretty sure that the failure is because of that and that enabling background indexing would fix it. Since I’m unable to act upon this issue as-is, I’m closing it. If you do get a chance to try again after performing a build or gather log output from the issue by running `sourcekit-lsp diagnose` after reproducing the issue, please re-open the issue with that additional information.

**Closed by ahoppen** 2024-12-04 04:16 UTC
Labels: bug
