### ISSUE TITLE
SourceKit-LSP use of CPU

### ISSUE THREAD

**Issue by WillyAguilera1977** [swiftlang/sourcekit-lsp#1461] opened 2024-06-08 16:57 UTC
### Swift version

Swift  5.10

### Platform

Windows 10

### Editor

Visual Studio Code with Swift extension 1.10.0

### Does the issue reproduce with Swift 6?

I didn’t try

### Description

SourceKit-LSP in Visual Studio Code for Windows constantly uses the CPU at 14 15 percent, it doesn't stop.

### Steps to Reproduce

When you open a Swift project or folder and open a file, SourceKit-LSP uses the CPU at 14 or 15 percent and never stops.

**Comment by ahoppen** [comment] 2024-06-08 19:35
Synced to Apple’s issue tracker as rdar://129451482

**Comment by ahoppen** [comment] 2024-07-31 02:26
This seems to be a duplicate of https://github.com/apple/swift-corelibs-libdispatch/issues/820.

**Closed by ahoppen** 2024-07-31 02:26 UTC
Labels: bug
